[versions]
aboutlibraries = "14.0.0-b02"
bundler = "1.0.4"
commonUtils = "0.9.11"
datastorePreferences = "1.2.0"
gradle = "9.0.0"
gradke-secrets = "2.0.1"
hilt = "2.59.1"
kotlin = "2.3.0"
ksp = "2.3.5"
room = "2.8.4"
volley = "1.2.1"

[libraries]
bundler = { module = "com.github.skydoves:bundler", version.ref = "bundler" }
common-utils = { module = "io.github.lemkinator:common-utils", version.ref = "commonUtils" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }

[plugins]
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
android-application = { id = "com.android.application", version.ref = "gradle" }
gradle-secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "gradke-secrets" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
room = ["room-ktx", "room-runtime"]